pr:
  - 7.0

trigger:
  - 7.0

variables:
  - group: fabric-variables
  - template: .devops/templates/variables.yml

pool: 'Self Host Ubuntu'

jobs:
  - job: BuildTestLint
    workspace:
      clean: all
    steps:
      - template: .devops/templates/tools.yml

      - task: Bash@3
        inputs:
          inputs:
          filePath: yarn-ci.sh
        displayName: yarn

      - script: |
          yarn checkchange
        displayName: check change

      ## manually call this since lage is now used and it calls lint per package, not per repo
      - script: |
          yarn prelint
        displayName: do syncpack and lint-files checks

      ## only do scoped builds with PRs
      - script: |
          yarn buildci --no-cache --since $(targetBranch)
        displayName: build, test, lint (pr, scoped)
        condition: ne(variables['Build.SourceBranch'], 'refs/heads/7.0')

      ## duplicated build step, but without --since flag for 7.0 CI builds
      - script: |
          yarn buildci --no-cache
        displayName: build, test, lint (7.0)
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/7.0')

      - template: .devops/templates/cleanup.yml

  - job: Deploy
    workspace:
      clean: all
    steps:
      - template: .devops/templates/tools.yml

      - task: Bash@3
        inputs:
          filePath: yarn-ci.sh
        displayName: yarn

      ## only do scoped bundle with PRs
      - script: |
          yarn bundle --no-cache --grouped --since $(targetBranch)
        displayName: bundle (pr, scoped)
        condition: ne(variables['Build.SourceBranch'], 'refs/heads/7.0')

      ## duplicated for  7.0 CI builds
      - script: |
          yarn bundle --no-cache --grouped
        displayName: bundle (7.0)
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/7.0')

      ## This runs regardless of scope, the app will adapt to the scope as well
      - script: |
          yarn workspace @uifabric/pr-deploy-site generate:site
        displayName: generate PR Deploy Site

      - publish: $(Build.ArtifactStagingDirectory)
        artifact: Build-PR-$(Build.BuildNumber)

      - task: AzureUpload@2
        displayName: Upload PR deploy site
        inputs:
          azureSubscription: $(azureSubscription)
          BlobPrefix: '$(deployBasePath)'
          ContainerName: '$web'
          SourcePath: 'apps/pr-deploy-site/dist'
          storage: $(azureStorage)

      - task: GithubPRStatus@0
        displayName: 'Update PR deploy site github status'
        inputs:
          githubOwner: microsoft
          githubRepo: fluentui
          githubContext: 'Pull request demo site'
          githubDescription: 'Click "Details" to go to the deployed demo site for this pull request'
          githubTargetLink: 'https://$(deployHost)/$(deployBasePath)/'

      - template: .devops/templates/cleanup.yml

  - job: Screener
    workspace:
      clean: all
    steps:
      - template: .devops/templates/tools.yml

      - task: Bash@3
        inputs:
          filePath: yarn-ci.sh
        displayName: yarn

      - script: |
          yarn lage screener --to vr-tests --debug --verbose --no-cache --grouped
        displayName: run VR Test
        env:
          SCREENER_API_KEY: $(screener.key)

      - template: .devops/templates/cleanup.yml
